# Generated by Django 6.0.3 on 2026-03-08 00:09

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_heroslide_gradient_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='background_image',
            field=models.ImageField(help_text='Recommended size: 1920x800px', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='hero_slides/'),
        ),
    ]
