# Generated by Django 6.0.3 on 2026-03-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_heroslide_background_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'slug')},
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='background_image',
            field=models.ImageField(help_text='Recommended size: 1920x800px', upload_to='hero_slides/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (0, 1, 2…)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(help_text='Main heading', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Extracted automatically from youtube_url', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
    ]
